services:
  api:
    container_name: api
    image: soilapt-api:latest
    volumes:
      - /home/kabum/dev/soil-apt/files:/usr/src/app/db
    ports:
      - 3001:3001
    env_file:
      - path: .env

  bot:
    container_name: bot
    depends_on:
      - api
    image: soilapt-bot:latest
    env_file:
      - path: .env
