name: CI - Api

on:
  pull_request:
    branches: [main]
    paths:
      - 'api/**/*.ts'

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: install
        run: bun install
      - name: lint API
        if: always()
        run: bun api:lint
