name: CI - Bot

on:
  pull_request:
    branches: [main]
    paths:
      - 'bot/**/*.ts'

defaults:
  run:
    working-directory: bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: install
        run: bun install
      - name: lint BOT
        if: always()
        run: bun bot:lint
