name: Deploy API and BOT

on:
  push:
    branches:
      - main
    paths:
      - api/**
      - bot/**
      - common/**
      - package.json
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S service soilapt-api stop
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S service soilapt-bot stop
            cd soil-apt
            git checkout main
            git pull 
            bun install
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S service soilapt-api start
            bun bot:deploy
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S service soilapt-bot start
