name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - name: install
        run: npm install
      - name: lint API
        run: npm run api:lint
      - name: lint bot
        run: npm run bot:lint
